# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLWyJcMFBNjl0H4aUXQzPk5RzPrfcUBE
"""

pip install pandas

import pandas as pd
variable = pd.read_html('https://en.wikipedia.org/wiki/Muhammad_Ishaq_Madni')

variable