# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCZocXywucd7X_MDSdbdXDtepegqNypu
"""

pip install pandas

import pandas as pd
variable = pd.read_csv('https://www.football-data.co.uk/new/IRL.csv')

variable

